### ISSUE TITLE
Fully static linking

### ISSUE THREAD

**Issue by nh2** [vaibhavsagar/experiments#6]
OK you totally sniped me with this, but here we go:

I've managed to esentially fully solve #5, doing fully static linking, by not using glibc, but a fully `musl` based tool chain.

Here: https://github.com/nh2/static-haskell-nix

At the time of writing, it's at [this commit](https://github.com/nh2/static-haskell-nix/blob/8aa81a08cf9b895537ad28dbfd30d4cd0a538f82/default.nix).

This is based on work of @dtzWill (such as https://github.com/NixOS/nixpkgs/pull/34645 and especially this https://github.com/NixOS/nixpkgs/pull/37598#issuecomment-375117019).

CC @angerman @bgamari, some of your work is paying off big time here.

**Comment by vaibhavsagar** [comment]
I'm trying this now and I'm unable to reproduce your results. `ghc841` isn't present (I replaced it with `ghc842`) and `libiconv` doesn't have an `override` attribute (not sure how to fix this). Is there something I'm doing wrong? I used the same command as your README. I'd love to include this in the blog post but I'd like to be able to reproduce your results first :smiley:.

**Comment by nh2** [comment]
I made a mistake, using a branch name to refer to the nixpkgs commit:

```
NIX_PATH=nixpkgs=https://github.com/dtzWill/nixpkgs/archive/feature/ghc-cross-musl.tar.gz
````

I thought `feature/ghc-cross-musl.tar.gz` was a tag and thus stable, but it was a branch, and it looks like it was just pushed from the previous commit `7048fc71e325c69ddfa62309c0b661b430774eac` to `6cc5483b5e94dfdcb17f46dd839fedf1f63122c3`.

I should have used:

```
NIX_PATH=nixpkgs=https://github.com/dtzWill/nixpkgs/archive/7048fc71e325c69ddfa62309c0b661b430774eac.tar.gz
````

I have now force-pushed my repo (usually foce-pushing master isn't nice but I wrote down wrote these things down in the commit messages for reproducibility, so that's more important to me to get right).

Could you try again?

**Comment by nh2** [comment]
The push in question is this one: https://github.com/NixOS/nixpkgs/issues/37522#ref-commit-1e28373

**Comment by vaibhavsagar** [comment]
It worked! I've updated my blog post accordingly.
