### ISSUE TITLE
Missing Full fast-path for HAMT

### ISSUE THREAD

**Issue by ekmett** [vaibhavsagar/experiments#7]
When the node in a HAMT is full, you can avoid all the popcounting overhead, which usually makes it worth special casing. Was sad when after 5 minutes of adding random nodes to finally get the root to be made of all 1s that it didn't switch from `Many` to another case, like we have in `unordered-containers`. ;)

**Comment by vaibhavsagar** [comment]
This is intentional! I wanted the implementation to be as simple as possible and I copied it straight from https://vaibhavsagar.com/blog/2018/07/29/hamts-from-scratch/. A production-ready implementation would support full nodes and collisions (as indicated in that blog post).

**Comment by vaibhavsagar** [comment]
@ekmett I updated it with support for `Full` in https://github.com/vaibhavsagar/experiments/commit/a6184f9a49d1a1e2200cca39a2cd3eee9adb5790, thanks for raising this!

**Comment by vaibhavsagar** [comment]
You can test this by using the numbers 0-9, 18-19, 22-23, and 26-27 as keys.
